#!/bin/bash

# Script per obrir totes les landing pages en pestanyes de Safari
# Executa: ./open_landing_pages.sh

echo "Obrint totes les landing pages en Safari..."

# Array amb tots els enllaços
links=(
    "https://github.com/nordicgiant2/react-nice-resume"
    "https://github.com/wonderfullandingpage/mylandingpage"
    "https://github.com/nordicgiant2/vue-nice-homepage"
    "https://github.com/wonderfullandingpage/Technology-LandingPage"
    "https://github.com/wonderfullandingpage/react-exquisite-resume"
    "https://github.com/nordicgiant2/gh-pages-theme"
    "https://github.com/StartBootstrap/startbootstrap-landing-page"
    "https://github.com/flexdinesh/dev-landing-page"
    "https://github.com/swcool/landing-page-theme"
    "https://github.com/nordicgiant2/sn-landing-page"
    "https://github.com/nordicgiant2/cool-landing"
    "https://github.com/carlsednaoui/ouibounce"
    "https://github.com/ant-design/ant-design-landing"
    "https://github.com/Esri/esri.github.io"
    "https://github.com/tailwindtoolbox/Landing-Page"
    "https://github.com/StartBootstrap/startbootstrap-new-age"
    "https://github.com/cssninjaStudio/fresh"
    "https://github.com/dennybritz/neal-react"
    "https://github.com/adrienjoly/landing-page-boilerplate"
    "https://github.com/vercel/spr-landing"
    "https://github.com/smartergiving/free-nonprofit-starter-website"
    "https://github.com/kriasoft/AngularJS-SPA-Template"
    "https://github.com/amiechen/codrops-scribbler"
    "https://github.com/akashgiricse/templates-using-bootstrap4"
    "https://github.com/jglovier/resume-template"
    "https://github.com/joashp/material-design-template"
    "https://github.com/StartBootstrap/startbootstrap-one-page-wonder"
    "https://website-templates.github.io/portfolio_one-page-template"
    "https://github.com/sproogen/modern-resume-theme"
    "https://github.com/ahmedhamodi/ahmedhamodi.github.io"
    "https://github.com/byoungd/Resume-template-for-Coder"
    "https://github.com/StartBootstrap/startbootstrap-shop-homepage"
    "https://github.com/StartBootstrap/startbootstrap-business-frontpage"
    "https://github.com/StartBootstrap/startbootstrap-heroic-features"
    "https://github.com/micua/home"
    "https://github.com/madzadev/landing-page"
    "https://github.com/divyu135/moodify-playlist"
    "https://github.com/Tomotoes/HomePage"
    "https://github.com/happypeter/happypeter.github.com"
    "https://github.com/brikis98/yevgeniy-brikman-homepage"
    "https://github.com/omegasisters/homepage"
    "https://github.com/yourfirstpr/yourfirstpr.github.io"
    "https://github.com/Jaredk3nt/homepage"
    "https://github.com/gitname/react-gh-pages"
    "https://github.com/ImedAdel/automatic-gatsbyjs-app-landing-page"
    "https://github.com/xriley/AppKit-Landing-Theme"
    "https://github.com/coala/landing-frontend"
    "https://github.com/ITRav4/PlexRedirect"
    "https://github.com/singhkshitij/My-Landing-Page"
    "https://github.com/sandoche/Mobile-app-landingpage-template"
    "https://github.com/JayantGoel001/JayantGoel001.github.io"
    "https://github.com/caarlosdamian/react-website-portafolio"
    "https://github.com/Blazity/next-saas-starter"
    "https://github.com/doniwirawan/Gradient-Landing-Page"
    "https://unbounce.com/landing-page-templates/"
    "https://unbounce.com/landing-page-template/freshgoods/"
    "https://themeforest.net/category/marketing/landing-pages"
    "https://dev.to/davidepacilio/40-free-html-landing-page-templates-3gfp"
    "https://startbootstrap.com/themes/landing-pages/"
    "https://onepagelove.com/templates/landing-page-templates"
    "https://elements.envato.com/web-templates/landing-page-templates"
    "https://wix.com/website/templates/html/landing-pages"
    "https://www.templatemonster.com/landing-page-templates.php"
    "https://www.creative-tim.com/bootstrap-themes/landing-page"
    "https://business.tutsplus.com/articles/mobile-app-landing-page--cms-32098"
    "https://business.tutsplus.com/articles/product-landing-page-examples--cms-32174"
    "https://webflow.com/templates/html/launcher-one-page-website-template"
    "https://www.abtasty.com/blog/bootstrap-landing-page-templates/"
    "https://www.mailerlite.com/landing-page-examples"
    "https://creativemarket.com/templates/websites/landing-pages"
    "https://colorlib.com/wp/templates/"
    "https://templated.co/"
    "https://www.templatemonster.com/"
    "https://www.free-css.com/free-css-templates"
    "https://templatemo.com/"
    "https://mobirise.com/bootstrap-template/homepage-template/"
    "https://www.learnworlds.com/course-landing-page-with-examples/"
    "https://foundr.com/online-course-landing-page"
    "https://mdbootstrap.com/education/bootstrap/landing-page-lesson-1/"
    "https://instapage.com/blog/landing-page-tutorial"
    "https://mailchimp.com/help/create-a-landing-page/"
    "https://webflow.com/feature/landing-page-tutorial"
    "https://www.crazyegg.com/blog/landing-page-essentials/"
    "https://www.javatpoint.com/landing-pages"
    "https://www.madza.dev/blog/create-a-landing-page-in-less-than-100-lines-incl-css"
    "https://www.youtube.com/watch?v=cKFy0SFZBdM"
    "https://www.youtube.com/watch?v=K8BigvW7sZU"
    "https://www.mailerlite.com/video-tutorials/landing-page"
    "https://unbounce.com/how-to-create-a-landing-page/"
    "https://workshops.unbounce.com/workshop/learn-to-create-an-unbounce-landing-page-from-scratch/"
    "https://neilpatel.com/blog/beginners-guide-to-landing-pages/"
    "https://medium.com/better-programming/how-to-build-a-landing-page-in-ten-minutes-11931e7f01f7"
    "https://websitesetup.org/bootstrap-tutorial-for-beginners/"
    "https://www.wix.com/blog/2015/11/create-a-powerful-free-landing-page-in-under-an-hour/"
    "https://academy.hubspot.com/lessons/creating-landing-pages-in-hubspot"
    "https://www.freecodecamp.org/news/learn-bootstrap-4-in-30-minute-by-building-a-landing-page-website-guide-for-beginners-f64e03833f33/"
    "https://elementor.com/blog/create-wordpress-landing-page/"
    "https://optinmonster.com/how-to-create-a-landing-page/"
    "https://thrivetracker.com/blog/how-to-build-a-simple-landing-page-using-dreamweaver/"
    "https://www.wpbeginner.com/wp-tutorials/how-to-create-a-landing-page-with-wordpress/"
    "https://www.wordstream.com/blog/ws/2014/02/12/great-landing-pages"
    "https://www.tutlane.com/tutorial/bootstrap"
    "https://cssauthor.com/landing-page-templates-psd/"
    "https://designsmaz.com/free-landing-page-psd-templates/"
    "https://speckyboy.com/free-landing-page-psd-web-templates/"
    "https://365webresources.com/free-landing-page-single-page-psd-templates/"
    "https://www.template.net/design-templates/psd/psd-landing-page-templates/"
    "https://freepsdfiles.net/website-templates/free-psd-landing-page-templates"
    "https://utemplates.net/app-landing-page-psd-templates/"
    "https://blog.hubspot.com/marketing/landing-page-examples-list"
    "https://freebiesbug.com/psd-freebies/free-psd-landing-page/"
    "https://bashooka.com/freebie/20-free-landing-page-templates/"
    "https://www.graphberry.com/category/themes"
    "https://dribbble.com/tags/free_landing_page"
    "https://psdrepo.com/free-psd/product-landing-page-template-2-freebie/"
    "https://freebies.fluxes.com/portfolio-landing-page-psd-html/"
    "https://pinspiry.com/seo-landing-page-free-psd/"
    "https://free-psd-templates.com/25-free-psd-landing-pagesfor-creative-amd-important-ideas/"
)

# Obrir Safari si no està obert
if ! pgrep -x "Safari" > /dev/null; then
    open -a Safari
    sleep 2
fi

# Obrir cada enllaç en una nova pestanya
for link in "${links[@]}"; do
    echo "Obrint: $link"
    open -a Safari "$link"
    sleep 0.5  # Petita pausa per evitar sobrecàrrega
done

echo "Totes les landing pages s'han obert en Safari!"
echo "Total d'enllaços oberts: ${#links[@]}"
